### ISSUE TITLE
no long distance mining

### ISSUE THREAD

**Issue by Matuiss2** [Matuiss2/Greedy_bot#162]
On the rare cases where this is needed it doesn't do it

**Comment by Helfull** [comment]
can you explain this a bit more? Why should it be required to long distance mine?

**Comment by Matuiss2** [comment]
On proxy defense, it doesn't expand until the proxy is gone, and in rare cases(1 in 20) it holds the pressure but the main gets mined out leading to a draw. The solution to that is improving the defense vs proxies but having long distance mining cant hurt
