### ISSUE TITLE
Only hatcheries get cancelled when attacked

### ISSUE THREAD

**Issue by Matuiss2** [Matuiss2/Greedy_bot#72]
and very badly too, I want to extend that to most buildings and improve the existing one

**Comment by tweakimp** [comment]
i dont think i have seen the existing one working yet

**Comment by Matuiss2** [comment]
Yeah the logic is not very good, I saw it working vs early pushes tho

**Comment by Matuiss2** [comment]
Should be fixed in #92

**Comment by Matuiss2** [comment]
Fixed in #92 confirmed
