### ISSUE TITLE
Terran walls are not targeted

### ISSUE THREAD

**Issue by Helfull** [Matuiss2/Greedy_bot#79]
![image](https://user-images.githubusercontent.com/720645/46570941-cabf8480-c96c-11e8-8b3b-eeac0df160b3.png)
![image](https://user-images.githubusercontent.com/720645/46570944-d01ccf00-c96c-11e8-8d3f-3a6b305a9484.png)

**Comment by tweakimp** [comment]
Do we have to add a path Check for every Attack? Or maybe for the targets that are at a different height.

**Comment by Matuiss2** [comment]
They are below units in prioritization thats why they were not attacked, our army tried to attack the units behind the wall, yeah this have to change

**Comment by Matuiss2** [comment]
Probably fixed on #102 Still have to confirm on the ladder

**Comment by Matuiss2** [comment]
It failed

**Comment by Matuiss2** [comment]
fixed
