### ISSUE TITLE
Defend cannon rush

### ISSUE THREAD

**Issue by tweakimp** [Matuiss2/Greedy_bot#91]
**Strategy:**

- Put overlord over natural
- Pull 3 Drones for every building and 1 Drone for every Probe.
- Attack lowhp buildings first, attack cannons over pylons.

**Comment by Matuiss2** [comment]
Make it 4 for every cannon and 1 for each probe and pylon

**Comment by tweakimp** [comment]
that is too few for the pylons, the cannons would get up too easily

**Comment by Matuiss2** [comment]
Ok, It would be something similar to the worker rush defense right? Thats a good idea

**Comment by tweakimp** [comment]
yes

**Comment by Matuiss2** [comment]
probably fixed on #102 still need to be tested on the ladder

**Comment by Matuiss2** [comment]
fixed in #133 at least simple ones
